PRAS	=	KASM
AS	=	MASM
ASFLAGS	=	
CPY	=	COPY
RAMDISK	=	E:\

..\EXEC\DATPL3A.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PARTST.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PARTT2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PARTT3.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PICTUER.OBJ	:	$*.ASM PICTUER.INC
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLSLD2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLSLD3.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLSLD4.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\VRMMOV.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTPAT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

