; "WORDID.INC" PC-9801UV11 make by R.H 1990/11/13
;
;
;	ＷＩＮＤＯＷＳ／単語ＩＤ
;
;
; (C) 1990 ritsurou hashimoto.

ID_00	EQU	00	; 無効		
ID_01	EQU	01	; 性別		
ID_02	EQU	02	; 星座		
ID_03	EQU	03	; 血液型		
ID_04	EQU	04	; 誕生日		
ID_05	EQU	05	; 年齢		
ID_06	EQU	06	; 身長		
ID_07	EQU	07	; 体重		
ID_08	EQU	08	; プロポー	
ID_09	EQU	09	; お金		
ID_10	EQU	10	; 体力		
ID_11	EQU	11	; 腕力		
ID_12	EQU	12	; 知力		
ID_13	EQU	13	; 気品		
ID_14	EQU	14	; 根性		
ID_15	EQU	15	; 疲労		
ID_16	EQU	16	; 色気		
ID_17	EQU	17	; モラル		
ID_18	EQU	18	; 評価		
ID_19	EQU	19	; 経験値		
ID_20	EQU	20	; 戦闘技術	
ID_21	EQU	21	; 素早さ		
ID_22	EQU	22	; 装甲強度	
ID_23	EQU	23	; 攻撃		
ID_24	EQU	24	; ＨＰ		
ID_25	EQU	25	; ＭＰ		
ID_26	EQU	26	; ナイフ		
ID_27	EQU	27	; こん棒		
ID_28	EQU	28	; メイス		
ID_29	EQU	29	; ショートソード	
ID_30	EQU	30	; ロングソード	
ID_31	EQU	31	; バトルアックス	
ID_32	EQU	32	; カタナ		
ID_33	EQU	33	; 皮の帽子	
ID_34	EQU	34	; 鉄兜		
ID_35	EQU	35	; 鉄仮面		
ID_36	EQU	36	; 皮鎧		
ID_37	EQU	37	; 鎖かたびら	
ID_38	EQU	38	; 鉄の鎧		
ID_39	EQU	39	; ビキニの鎧	
ID_40	EQU	40	; 盾		
ID_41	EQU	41	; 薬草		
ID_42	EQU	42	; ぬいぐるみ	
ID_43	EQU	43	; かわいい便箋	
ID_44	EQU	44	; 本		
ID_45	EQU	45	; 詩集		
ID_46	EQU	46	; ティーカップ	
ID_47	EQU	47	; ドレス		
ID_48	EQU	48	; 攻撃魔法	
ID_49	EQU	49	; 防御魔法	
ID_50	EQU	50	; 治療魔法	
ID_51	EQU	51	; ブレス		
ID_52	EQU	52	; 宿屋		
ID_53	EQU	53	; 酒屋		
ID_54	EQU	54	; 武器屋		
ID_55	EQU	55	; 教会		
ID_56	EQU	56	; メイド		
ID_57	EQU	57	; 医者		
ID_58	EQU	58	; あやしい宿屋	
ID_59	EQU	59	; あやしい酒場	
ID_60	EQU	60	; 代筆屋		
ID_61	EQU	61	; 狩人		
ID_62	EQU	62	; 木コリ		
ID_63	EQU	63	; 人足		
ID_64	EQU	64	; 訓練		
ID_65	EQU	65	; 武芸		
ID_66	EQU	66	; 学問		
ID_67	EQU	67	; 礼法		
ID_68	EQU	68	; 武者修行	
ID_69	EQU	69	; 休息		
ID_70	EQU	70	; アルバイト	
ID_71	EQU	71	; バカンス	
ID_72	EQU	72	; 初級
ID_73	EQU	73	; 中級
ID_74	EQU	74	; 上級
ID_75	EQU	75	; 春のバカンス
ID_76	EQU	76	; 夏のバカンス
ID_77	EQU	77	; 秋のバカンス
ID_78	EQU	78	; 冬のバカンス
ID_79	EQU	79	; 学問初級合格証
ID_80	EQU	80	; 学問中級合格証
ID_81	EQU	81	; 学問上級合格証
ID_82	EQU	82	; 武芸初級合格証
ID_83	EQU	83	; 武芸中級合格証
ID_84	EQU	84	; 武芸上級合格証
ID_85	EQU	85	; やめる
ID_86	EQU	86	; 何も装備しない
ID_87	EQU	87	; リゲイン
ID_88	EQU	88	; おひつじ座
ID_89	EQU	89	; おうし座
ID_90	EQU	90	; ふたご座
ID_91	EQU	91	; かに座	
ID_92	EQU	92	; しし座	
ID_93	EQU	93	; おとめ座
ID_94	EQU	94	; てんびん座
ID_95	EQU	95	; さそり座
ID_96	EQU	96	; いて座	
ID_97	EQU	97	; やぎ座	
ID_98	EQU	98	; みずがめ座
ID_99	EQU	99	; うお座	
ID_100	EQU	100	; 女の子
ID_101	EQU	101	; 女
ID_102	EQU	102	; 男
ID_103	EQU	103	; 中性
ID_104	EQU	104	; Ａ型
ID_105	EQU	105	; ＡＢ型
ID_106	EQU	106	; Ｂ型
ID_107	EQU	107	; Ｏ型
ID_108	EQU	108	; ＋α		; 1991/01/16
ID_109	EQU	109	; やりなおし
ID_110	EQU	110	; ニードル
ID_111	EQU	111	; ファイア
ID_112	EQU	112	; マジックミサイル
ID_113	EQU	113	; バリア
ID_114	EQU	114	; ヒール
ID_115	EQU	115	; サンダー
ID_116	EQU	116	; 好戦度
ID_117	EQU	117	; 剣士
ID_118	EQU	118	; 上級剣士
ID_119	EQU	119	; 剣聖
ID_120	EQU	120	; 二級学士
ID_121	EQU	121	; 一級学士
ID_122	EQU	122	; 博士


WD_ADRS		MACRO	IDD,DEST
	MOV	ES,SEGWID		;
	MOV	DI,WIDOFS_ENVIR		; 環境テーブル
	MOV	BX,ES:[DI]		;
	ADD	BX,IDD*2		;
	MOV	AX,ES:[BX]		;
	MOV	DEST,AX			;
	ENDM

WD_CMP		MACRO	IDD,DEST
	MOV	ES,SEGWID		;
	MOV	DI,WIDOFS_ENVIR		; 環境テーブル
	MOV	BX,ES:[DI]		;
	ADD	BX,IDD*2		;
	MOV	AX,ES:[BX]		;
	CMP	DEST,AX			;
	ENDM


;	アイテム属性

IDZ_01	EQU	1	; 属武器
IDZ_02	EQU	2	; 属防具・兜
IDZ_03	EQU	3	; 属防具・鎧
IDZ_04	EQU	4	; 属防具・盾
IDZ_05	EQU	5	; 属道具
IDZ_06	EQU	6	; 属資格

;
;	end of "WORDID.INC"
;
