PRAS	=	KASM
AS	=	MASM
ASFLAGS	=	
CPY	=	COPY
RAMDISK	=	E:\

..\EXEC\CMDTBL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\CMDTOOL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\CONSOLE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\GRBIO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\KOSODATE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\KOSOMAIN.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\MACLIB.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\TIMER.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\TSTKS1.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\VRTEXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\MINTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\MIDTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\MIWTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\MIBTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\MGXTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\HVLINE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\EFECT2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\DSPSET.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\RANDAM.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTSET.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTTBL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\ADVPLT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\DISKIO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\DSKCHG.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\TALKER.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\ADVMOV.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\IPLMSG.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\TXTATR.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\OVLAP.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\EMEMORY.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\EMSHND.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

..\EXEC\EMSDRV.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;
	$(CPY) $@ $(RAMDISK)

