AS	=	MASM
ASFLAGS	=	

MACLIB.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

KASM.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

DISKIO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

GETARG.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM,$@;

